config/routes.rb
Rails.application.routes.draw do
  resources :images, only: [:index, :new, :create], path: '/imagenes'
end

app/models/image.rb
class Image < ActiveRecord::Base
	enum category: %w(portrait landscape city\ exploration nature animals)

	validates :name, presence: true

	def tags_text
		#self.tags.join(', ')
	end

	def tags_text=(value)
		self.tags = value.split(',').map{ |tag| tag.strip}
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
	
	def index
	end

	def new
		@image = Image.new
	end

	def create
		@image = Image.new secure_params
		
		if @image.save
			return redirect_to images_path, notice: t('.created', model: @image.class.model_name.human)
		end
		render :new
	end

	private

	def secure_params
		params.require(:image).permit :name, :description, :category, :tags_text
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def image_categories
		Image.categories.inject({}) do |hash, elem|
			hash.merge!(t("categories.#{elem.first.gsub(' ', '_')}") => elem.first)
		end
	end
end

app/views/images/index.html.erb
<h1><%= t('.title') %></h1>

<p>
	<%= link_to t('.new_link'), new_image_path %>
</p>

app/views/images/new.html.erb
<% model_name = @image.class.model_name.human %>
<h1><%= t('.title', model: model_name) %></h1>

<%= form_for @image, builder: CustomFormBuilder do |f| %>
	<%= f.form_error %>
	<div class="field">
		<%= f.label :name %>
		<%= f.text_field :name %>
		<%= f.field_error :name %>
	</div>
	<div class="field">
		<%= f.label :description %>
		<%= f.text_area :description %>
	</div>
	<div class="field">
		<%= f.collection_select :category, image_categories, :last, :first %>
	</div>
	<div class="field">
		<%= f.label :tags_text %>
		<%= f.text_field :tags_text %>
	</div>
	<div class="field">
		<%= f.submit %>
	</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Onepx</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div id="flash">
		<% flash.each do |key, value| %>
			<div id="flash-<%= key %>"><%= value %></div>
		<% end %>
	</div>
	<%= yield %>
</body>
</html>